import { AREAS, escapeHtml } from './domain.mjs';
import { DemoClient, HttpClient } from './client.mjs';

const api = new DemoClient();
const e = escapeHtml;
const paths = {
  spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',
  home:'m3 10 9-7 9 7M5 9v11h14V9M9 20v-7h6v7',
  shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z M9 12l2 2 4-4',
  plus:'M12 5v14M5 12h14', arrow:'M5 12h14m-5-5 5 5-5 5',
  chevron:'m9 5 7 7-7 7', close:'m6 6 12 12M6 18 18 6',
  book:'M12 5v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2Z',
  chart:'M4 3v17h17M8 15l4-5 4 2 5-7', user:'M5 21v-2a7 7 0 0 1 14 0v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  heart:'M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z',
  folder:'M3 6h7l2 2h9v12H3Z M3 6V4h7l2 2h7v2', calendar:'M4 5h16v16H4ZM4 10h16M8 3v4M16 3v4',
  check:'m5 12 4 4L19 6', tasks:'M9 5h11M9 12h11M9 19h11M3 5h1M3 12h1M3 19h1',
  search:'M16 10a6 6 0 1 1-12 0 6 6 0 0 1 12 0m-2 4 6 6',
  chat:'M3 4h18v13H8l-5 4Z', monitor:'M3 4h18v13H3ZM12 17v4M7 21h10',
  lock:'M5 10h14v11H5ZM8 10V6a4 4 0 0 1 8 0v4M12 14v3',
  settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',
  code:'m8 5-7 7 7 7m8-14 7 7-7 7m-3-17-2 20', moon:'M20 14a9 9 0 0 1-10-11 9 9 0 1 0 10 11',
  info:'M12 8h.01M12 11v6M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
  file:'M5 2h9l5 5v15H5ZM14 2v6h5M8 12h8M8 16h6', save:'M3 3h15l3 3v15H3ZM7 3v6h9V3M7 21v-8h10v8',
  clock:'M12 7v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
  menu:'M4 6h16M4 12h16M4 18h16', send:'m3 3 19 9-19 9 4-9Zm4 9h15',
  cloud:'M6 18a5 5 0 1 1 0-10 7 7 0 0 1 13-1 5.5 5.5 0 0 1-1 11Z',
  refresh:'M20 7A9 9 0 1 0 21 15M20 3v5h-5', download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',
  layers:'m12 3 10 5-10 5L2 8Zm-10 9 10 5 10-5M2 16l10 5 10-5'
};
function icon(name) { return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.spark}"/></svg>`; }
function btn(label, action, kind='', extra='') { return `<button class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`; }
function area(id) { return AREAS.find(a=>a.id===id) || {id:'general',name:'General',icon:'spark',color:'purple'}; }
function options(selected='general') { return [{id:'general',name:'General'},...AREAS].map(a=>`<option value="${a.id}" ${a.id===selected?'selected':''}>${e(a.name)}</option>`).join(''); }
const state={view:'home', chatId:null, category:'', filter:'', menu:false, sidebarCollapsed:false, month:8, year:2026, computer:'idle', busy:false};
const titles={home:'Inicio',chat:'Conversación',history:'Conversaciones',files:'Archivos',calendar:'Calendario',tasks:'Tareas',knowledge:'Conocimiento',agents:'Agentes',accounts:'Cuentas e integraciones',computer:'Ordenadores',developer:'Developer',settings:'Ajustes',audit:'Registro de actividad'};
const mount=document.querySelector('#app');
const dialog=document.querySelector('#dialog');
let toastTimer;
function toast(message) { const el=document.querySelector('#toast'); el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4800); }
function modal(title, html) { dialog.innerHTML=`<div class="modal-head"><h2>${e(title)}</h2><button class="icon-btn" data-action="close" aria-label="Cerrar diálogo">${icon('close')}</button></div>${html}`;dialog.showModal(); }
function nav(view) {state.view=view;state.menu=false;state.filter='';state.category='';history.replaceState(null,'',`#${view}`);render().then(()=>document.querySelector('#main')?.focus());}
function navItem(view,label,ico) { return `<button class="nav-item ${state.view===view?'active':''}" data-nav="${view}" ${state.view===view?'aria-current="page"':''}>${icon(ico)}<span>${label}</span></button>`; }
function sidebar() {return `<button class="menu-shade" data-action="menu" aria-label="Cerrar navegación"></button><aside class="sidebar" aria-label="Navegación principal">
<div class="sidebar-top"><button class="brand" data-nav="home" aria-label="Lisa, inicio"><span class="logo">L</span><span class="brand-copy"><strong>lisa</strong><small>ESPACIO PERSONAL</small></span></button><button class="collapse-btn" data-action="sidebar-collapse" aria-label="${state.sidebarCollapsed?'Expandir':'Contraer'} menú">${icon('menu')}</button></div>
<button class="new-chat primary" data-new="general">${icon('spark')}<span>Con conocimiento</span>${icon('plus')}</button>
<button class="new-chat" data-new="sandbox">${icon('shield')}<span>Nuevo chat Sandbox</span>${icon('plus')}</button>
<div class="nav-group">${navItem('home','Inicio','home')}${navItem('history','Conversaciones','chat')}</div>
<div class="nav-group"><div class="nav-label">Tus agentes</div>${AREAS.map(a=>`<button class="nav-item" data-agent="${a.id}" title="${e(a.name)}">${icon(a.icon)}<span>${a.name}</span><i class="dot" aria-hidden="true"></i></button>`).join('')}</div>
<div class="nav-group"><div class="nav-label">Tu espacio</div>${navItem('files','Archivos','folder')}${navItem('calendar','Calendario','calendar')}${navItem('tasks','Tareas','tasks')}${navItem('knowledge','Conocimiento','layers')}</div>
<div class="sidebar-bottom">${navItem('computer','Ordenadores','monitor')}${navItem('accounts','Cuentas','lock')}${navItem('developer','Developer','code')}${navItem('settings','Ajustes','settings')}<div class="profile"><span class="avatar">L</span><div><strong>Mi espacio</strong><small>Preview · datos ficticios</small></div></div></div></aside>`;}
function topbar(){return `<header class="topbar"><button class="icon-btn mobile-menu" data-action="menu" aria-label="Abrir navegación" aria-expanded="${state.menu}">${icon('menu')}</button><div class="breadcrumb">Mi espacio ${icon('chevron')} <strong>${e(titles[state.view]||'Inicio')}</strong></div><div class="topbar-right"><span class="pill">${icon('spark')} Preview 0.4</span><button class="icon-btn" data-action="audit" aria-label="Ver registro de actividad">${icon('clock')}</button></div></header>`;}
const banner=()=>`<div class="demo-note">${icon('info')}<span>Demostración interactiva. Solo datos ficticios; sin IA ni servicios conectados. Los cambios se pierden al recargar. No introduzcas información personal.</span></div>`;
function heading(title,desc,action=''){return `<div class="view-heading"><div><h1>${e(title)}</h1><p>${e(desc)}</p></div>${action}</div>`;}
function section(title,action=''){return `<div class="section-head"><h2>${title}</h2>${action}</div>`;}
function empty(title,description,action=''){return `<div class="empty">${icon('layers')}<h3>${title}</h3><p>${description}</p>${action}</div>`;}
function taskRow(t){return `<div class="list-row ${t.done?'done':''}"><button class="check ${t.done?'checked':''}" data-task="${e(t.id)}" data-done="${t.done}" aria-label="${t.done?'Marcar pendiente':'Completar'}: ${e(t.title)}">${t.done?icon('check'):''}</button><div><strong>${e(t.title)}</strong><small>${e(area(t.category).name)} · ejemplo</small></div></div>`;}
function eventRow(v){return `<div class="list-row"><div class="mini-date">${e(v.time)}</div><div><strong>${e(v.title)}</strong><small>${e(v.date)} · ${e(area(v.category).name)}</small></div></div>`;}
async function home(){return document.querySelector('#home-dashboard').innerHTML;}
async function chatView(){if(!state.chatId)return empty('Elige cómo empezar','Con tu conocimiento personal o desde un espacio Sandbox.',`${btn('Con conocimiento','new-general','primary')} ${btn('Sandbox','new-sandbox')}`);const c=await api.request('GET',`/chats/${state.chatId}`);const sandbox=c.mode==='sandbox';const name=c.mode==='agent'?area(c.agentId).name:sandbox?'Sandbox':'Con conocimiento';return `${heading(name,sandbox?'Explora sin utilizar tu conocimiento personal.':'Un espacio para preguntar y conectar ideas.')}
<div class="chat-layout"><div class="chat-panel"><div class="chat-heading"><h2>${e(c.title)}</h2><span class="pill ${sandbox?'neutral':''}">${icon(sandbox?'shield':'spark')}${sandbox?'Sandbox · demo':'Contexto · demo'}</span></div><div class="messages" id="messages">${c.messages.length?c.messages.map(m=>`<div class="message ${e(m.role)}"><span class="message-label">${m.role==='user'?'Tú':m.role==='imported'?'Contexto importado · no confiable':'Lisa · respuesta simulada'}</span>${e(m.content)}</div>`).join(''):`<div class="empty" style="border:0;padding-top:60px">${icon(sandbox?'shield':'spark')}<h3>${sandbox?'Un comienzo en blanco.':'¿Qué te gustaría poner en orden?'}</h3><p>${sandbox?'Sin documentos, calendario, credenciales ni memoria personal. En esta demo no hay un runtime real.':'En el sistema completo podrás consultar el conocimiento que autorices. Esta vista solo simula la conversación.'}</p>${btn('Probar con una pregunta','sample')}</div>`}</div><form class="composer" data-form="message"><label class="sr-only" for="message">Mensaje de prueba</label><textarea id="message" name="content" placeholder="Escribe un mensaje de prueba…" maxlength="8000" required></textarea><div class="composer-footer"><small>Sin modelo conectado · no uses datos reales</small><button class="btn primary" type="submit" ${state.busy?'disabled':''}>Enviar ${icon('send')}</button></div></form></div>
<aside class="context-card"><h3>Contexto de esta conversación</h3><p>${sandbox?'Nada de tu espacio personal se añade al contexto.':'El contexto dependerá de los permisos del agente, no de la carpeta donde guardes el chat.'}</p><div class="context-line"><span>Conocimiento</span><strong>${sandbox?'Ninguno':c.mode==='agent'?e(name):'General'}</strong></div><div class="context-line"><span>Historial</span><strong>${c.saved?'Guardado · demo':'Sin guardar'}</strong></div><div class="context-line"><span>Categoría</span><strong>${e(area(c.category).name)}</strong></div><div class="context-line"><span>Integraciones</span><strong>Ninguna</strong></div><span class="pill warning">Guardado ≠ memoria</span>${btn(`${icon('save')} Guardar`,'save-chat')}${btn(`${icon('folder')} Guardar en…`,'categorize')}${btn(`${icon('arrow')} Continuar con…`,'promote')}${btn(`${icon('layers')} Proponer conocimiento`,'extract','',c.saved?'':'disabled title="Guarda primero la conversación"')}${btn('Descartar chat','discard','danger')}</aside></div>`;}
async function historyView(){const chats=await api.request('GET','/chats?saved=true');return heading('Conversaciones','Solo aparecen las que has decidido guardar durante esta demostración.')+(chats.length?`<div class="panel">${chats.map(c=>`<button class="list-row list-button" data-chat="${e(c.id)}"><span class="tile-icon small">${icon(c.mode==='sandbox'?'shield':'chat')}</span><div><strong>${e(c.title)}</strong><small>${e(area(c.category).name)} · modo ${e(c.mode)} · guardado en memoria de la demo</small></div><span class="trailing">${icon('chevron')}</span></button>`).join('')}</div>`:empty('Aún no hay conversaciones guardadas','Inicia un chat y pulsa Guardar. La demo no conserva datos tras recargar.',btn('Empezar con conocimiento','new-general','primary')));}
async function filesView(){const files=await api.request('GET',`/files${state.category?'?category='+state.category:''}`);const filtered=files.filter(f=>f.name.toLocaleLowerCase().includes(state.filter.toLocaleLowerCase()));return heading('Tus archivos','La interfaz de Lisa; en el futuro, Nextcloud por debajo.',btn(`${icon('cloud')} Integración Nextcloud`,'nextcloud'))+`<div class="chips"><button class="chip ${!state.category?'active':''}" data-category="">Todos</button>${AREAS.map(a=>`<button class="chip ${state.category===a.id?'active':''}" data-category="${a.id}">${a.name}</button>`).join('')}<form data-form="search" style="margin-left:auto"><label class="sr-only" for="file-search">Buscar archivos</label><input id="file-search" name="query" value="${e(state.filter)}" placeholder="Buscar archivo…" style="border:1px solid var(--line);border-radius:8px;padding:6px 10px;background:var(--panel);color:var(--ink);max-width:170px"></form></div><div class="file-grid">${filtered.map(f=>`<button class="file-card" data-file="${f.id}"><div class="file-cover">${icon('file')}</div><strong>${e(f.name)}</strong><small>${e(area(f.category).name)} · ${f.size} · v${f.version}</small><div class="resource-line">ID estable de ejemplo · ${f.id}</div></button>`).join('')}</div>${!filtered.length?empty('No hay coincidencias','Prueba otra categoría o búsqueda.'):''}`;}
async function tasksView(){const list=await api.request('GET','/tasks');return heading('Una cosa cada vez','Organiza lo pendiente sin perder de vista el contexto.',btn(`${icon('plus')} Nueva tarea`,'new-task','primary'))+`<div class="chips"><span class="pill">${list.filter(t=>!t.done).length} pendientes</span><span class="pill neutral">${list.filter(t=>t.done).length} completadas</span><span class="pill neutral">Persistencia: solo esta demo</span></div><div class="panel">${list.map(taskRow).join('')}</div>`;}
async function calendarView(){const events=await api.request('GET','/events');const first=new Date(state.year,state.month,1);const offset=(first.getDay()+6)%7;const total=new Date(state.year,state.month+1,0).getDate();const month=first.toLocaleDateString('es',{month:'long',year:'numeric'});let cells='';for(let i=0;i<offset;i++)cells+='<div class="day blank"></div>';for(let d=1;d<=total;d++){const date=`${state.year}-${String(state.month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;cells+=`<button class="day ${date==='2026-09-23'?'today':''}" data-date="${date}" aria-label="Crear evento el ${date}"><span class="day-number">${d}</span>${events.filter(v=>v.date===date).map(v=>`<span class="day-event ${area(v.category).color}">${e(v.time)} ${e(v.title)}</span>`).join('')}</button>`;}return heading('Tu tiempo, con perspectiva','Calendario de muestra. La sincronización CalDAV todavía no está conectada.',btn(`${icon('plus')} Nuevo evento`,'new-event','primary'))+`<div class="calendar-toolbar"><button class="icon-btn" data-month="-1" aria-label="Mes anterior">←</button><h2>${e(month)}</h2><button class="icon-btn" data-month="1" aria-label="Mes siguiente">→</button><span class="pill neutral">Fechas de ejemplo</span></div><div class="panel calendar-panel"><div class="calendar-grid">${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=>`<div class="day-name">${d}</div>`).join('')}${cells}</div></div>${section('Agenda de demostración')}<div class="panel">${events.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(eventRow).join('')}</div>`;}
async function knowledgeView(){const notes=await api.request('GET','/knowledge');return heading('Conocimiento, no ruido','Lo que decides conservar, con su procedencia y su estado.')+`<div class="note-box">Guardar una conversación no la añade automáticamente aquí. Puedes proponer una nota, revisarla y aprobarla por separado.</div><div class="grid-2">${notes.map(n=>`<article class="panel"><span class="pill ${n.status==='proposed'?'warning':''}">${n.status==='proposed'?'Pendiente de revisión':'Aprobado · demo'}</span><h3 style="margin:15px 0 9px">${e(n.title)}</h3><p style="font-size:12px;white-space:pre-wrap">${e(n.content)}</p><div class="resource-line">Fuente: ${e(n.source)} · ${e(area(n.category).name)}</div>${n.status==='proposed'?btn('Aprobar nota de ejemplo','approve-note','',`data-id="${n.id}" style="margin-top:15px"`):''}</article>`).join('')}</div>`;}
function agentsView(){return heading('Agentes con límites claros','Vista de la política propuesta. El backend deberá hacerla cumplir.')+`<div class="integration-grid">${AREAS.map(a=>`<article class="panel integration-card ${a.color}"><span class="tile-icon colored">${icon(a.icon)}</span><h3>${a.name}</h3><p>${a.description}</p><div class="pill neutral">Solo su área · sin cuentas conectadas</div><div style="margin-top:18px">${btn('Abrir conversación','start-agent','',`data-id="${a.id}"`)}</div></article>`).join('')}</div>${section('Matriz de permisos propuesta')}<div class="panel table-wrap"><table class="permission-table"><thead><tr><th>Identidad</th><th>Conocimiento</th><th>Calendario / tareas</th><th>Secretos en texto</th><th>Acciones sensibles</th></tr></thead><tbody><tr><td>General</td><td>Áreas autorizadas</td><td>Según permiso</td><td>No</td><td>Confirmación</td></tr>${AREAS.map(a=>`<tr><td>${a.name}</td><td>Solo ${a.name}</td><td>Ámbitos autorizados</td><td>No</td><td>Confirmación</td></tr>`).join('')}<tr><td>Sandbox</td><td>Ninguno</td><td>No</td><td>No</td><td>No</td></tr><tr><td>Developer</td><td>Código / fixtures</td><td>No por defecto</td><td>No</td><td>Revisión humana</td></tr></tbody></table></div>`;}
function accountsView(){return heading('Conexiones, bajo tu control','Ninguna cuenta está conectada en este prototipo.')+`<div class="integration-grid">${[{id:'nextcloud',icon:'cloud',name:'Nextcloud',desc:'Archivos, versiones, calendario y sincronización. Tu UI, sus APIs.'},{id:'1password',icon:'lock',name:'1Password',desc:'Un broker utilizará credenciales autorizadas. El modelo no recibirá acceso a tu bóveda.'},{id:'openclaw',icon:'spark',name:'OpenClaw',desc:'Runtime de agentes detrás de un adaptador. Sesiones privadas y Sandbox separadas.'},{id:'tasks',icon:'tasks',name:'Tareas / CalDAV',desc:'Primera opción de backend para tareas. Vikunja queda como alternativa.'},{id:'authorization',icon:'shield',name:'Autorización',desc:'Políticas aplicadas por el servidor. OpenFGA es una opción, no una dependencia de la UI.'},{id:'models',icon:'layers',name:'Modelos por API',desc:'Proveedor intercambiable. Sin claves, consumo de tokens ni llamadas a modelos en la demo.'}].map(i=>`<article class="panel integration-card"><span class="tile-icon">${icon(i.icon)}</span><h3>${i.name}</h3><span class="pill neutral">No conectado</span><p>${i.desc}</p>${btn('Ver contrato de integración','integration','',`data-id="${i.id}"`)}</article>`).join('')}</div>`;}
function computerView(){const label={idle:'Sin sesión activa',waiting:'Esperando intervención · simulación',human:'Control humano · simulación',paused:'Sesión detenida · simulación'}[state.computer];return heading('Cuando necesitas tomar el control','Vista de diseño. No hay escritorio remoto ni navegador conectado.')+`<div class="split"><div class="panel"><div class="btn-row" style="justify-content:space-between;margin-bottom:20px"><h3>Escritorio de una tarea</h3><span class="pill warning">Simulación</span></div><div class="screen"><div class="screen-inner">${icon('monitor')}<h3>${label}</h3><p>En producción verás aquí la misma sesión gráfica que utiliza el agente. El control deberá tener un único propietario.</p></div></div><div class="btn-row" style="margin-top:18px">${btn('Simular solicitud','computer-wait')}${btn('Tomar control','computer-take','primary',state.computer==='waiting'?'':'disabled')}${btn('Devolver control','computer-release','',state.computer==='human'?'':'disabled')}${btn('Detener','computer-stop')}</div></div><div class="panel"><h2>Intervención humana</h2>${[{title:'El agente se detiene',desc:'El runtime suspende las entradas antes de ceder la sesión.'},{title:'Tú completas el paso',desc:'Autenticación, permisos o confirmaciones que requieren una persona.'},{title:'Confirmas la continuación',desc:'El agente captura el estado actualizado y vuelve a evaluar la tarea.'}].map((s,i)=>`<div class="step"><b>${i+1}</b><div><strong>${s.title}</strong><p>${s.desc}</p></div></div>`).join('')}<div class="note-box warning">No se presupone compatibilidad nativa. El adaptador debe verificar pausa, control exclusivo, reconexión y captura en la versión concreta.</div></div></div>`;}
function developerView(){return heading('Lisa, a tu manera','Diseña cambios sin tocar tus datos ni la versión estable.',btn(`${icon('plus')} Proponer un cambio`,'dev-proposal','primary'))+`<div class="split"><div class="panel"><div class="eyebrow">Entorno de desarrollo</div><h2>Código separado de tu vida personal.</h2><p style="font-size:12px;margin-top:13px;line-height:1.9">Este panel será el punto de entrada para un agente programador, un editor y una terminal aislada. En esta versión solo puedes revisar el flujo propuesto.</p><pre class="code">$ git switch -c propuesta/cambio-ui\n$ ejecutar pruebas\n$ abrir preview\n\n# Vista ilustrativa. No se ejecutan comandos.\n# Sin acceso a documentos, secretos o producción.</pre>${btn('Terminal pendiente del backend','none','','disabled')}</div><div class="panel"><h2>Del cambio a la versión estable</h2>${[{title:'Propuesta',desc:'Describe el resultado deseado.'},{title:'Rama y preview',desc:'El agente trabaja sobre código y fixtures, no sobre datos privados.'},{title:'Pruebas y revisión',desc:'Ver diff, pruebas y permisos afectados.'},{title:'Aplicar o descartar',desc:'Publicar exige autorización. Conservar versión anterior para rollback.'}].map((s,i)=>`<div class="step"><b>${i+1}</b><div><strong>${s.title}</strong><p>${s.desc}</p></div></div>`).join('')}</div></div>`;}
async function auditView(){const rows=await api.request('GET','/audit');return heading('Actividad visible','Registro de interacciones simuladas. No es una auditoría de producción.')+(rows.length?`<div class="panel">${rows.map(r=>`<div class="timeline">${icon('check')}<div><strong style="font-size:12px">${e(r.action)}</strong><p>${e(r.resource)}</p></div><span class="pill neutral" style="margin-left:auto">${new Date(r.at).toLocaleTimeString('es')}</span></div>`).join('')}</div>`:empty('Todavía no hay actividad','Guarda un chat, crea una tarea o promueve una conversación para revisar el flujo.'));}
function settingsView(){return heading('Un sistema que puedas cambiar','Configuración y estado real de esta entrega.')+`<div class="grid-2"><div class="panel"><h2>Modo de demostración</h2><p style="font-size:12px;margin:15px 0;line-height:1.8">Los datos viven en memoria del navegador. No usamos almacenamiento local para mensajes ni enviamos tus textos a un servidor. Recargar elimina también las conversaciones marcadas como guardadas en la demo.</p><div class="btn-row">${btn('Reiniciar la demo','reset','danger')}${btn('Cambiar tema','theme')}</div></div><div class="panel"><h2>API preparada, backend pendiente</h2><p style="font-size:12px;margin:15px 0;line-height:1.8">Las vistas consumen un adaptador común. La base futura es <code>/api/v1</code>. Los endpoints privados no se abren sin autenticación: actualmente rechazan acciones con un error explícito de no implementado.</p>${btn('Comprobar endpoint','check-api')}</div><div class="panel"><h2>Revisar este diseño</h2><p style="font-size:12px;margin:15px 0;line-height:1.8">Prueba ambos chats, guarda uno, clasifícalo y continúa en otro agente. Revisa también los tamaños de móvil y el modo oscuro.</p>${btn(`${icon('download')} Descargar checklist`,'download-checklist')}</div><div class="panel"><h2>Sin conexiones ocultas</h2><p style="font-size:12px;margin:15px 0;line-height:1.8">Nextcloud, 1Password, OpenClaw, modelos, escritorio y terminal están pendientes. No se ha desplegado el servidor personal ni se han migrado archivos.</p>${btn('Ver integraciones','accounts')}</div></div>`;}
const views={home,chat:chatView,history:historyView,files:filesView,tasks:tasksView,calendar:calendarView,knowledge:knowledgeView,agents:agentsView,accounts:accountsView,computer:computerView,developer:developerView,audit:auditView,settings:settingsView};
async function render(){const body=await (views[state.view]||home)();mount.innerHTML=`<div class="shell ${state.menu?'menu-open':''} ${state.sidebarCollapsed?'collapsed':''}">${sidebar()}<div class="main-wrap">${topbar()}<main class="content" id="main" tabindex="-1">${banner()}${body}</main></div></div>`;document.title=`${titles[state.view]||'Inicio'} · Lisa`;if(state.view==='chat'){const box=document.querySelector('#messages');if(box)box.scrollTop=box.scrollHeight;}}
async function newChat(mode,agentId){const c=await api.request('POST','/chats',{mode,agentId});state.chatId=c.id;nav('chat');}
function eventModal(date='2026-09-23'){modal('Nuevo evento de ejemplo',`<form data-form="event"><label class="field">Título<input name="title" required maxlength="160" placeholder="¿Qué quieres organizar?"></label><div class="grid-2"><label class="field">Fecha<input type="date" name="date" value="${e(date)}" required></label><label class="field">Hora<input type="time" name="time" value="10:00" required></label></div><label class="field">Categoría<select name="category">${options()}</select></label><div class="modal-footer"><button class="btn primary" type="submit">Crear en la demo</button></div></form>`);}
async function handleAction(action,target){
 if(action==='close'){dialog.close();return;}
 if(action==='theme'){toast('Esta propuesta visual está fijada en modo claro.');return;}
 if(action==='menu'){state.menu=!state.menu;document.querySelector('.shell').classList.toggle('menu-open',state.menu);const b=document.querySelector('.mobile-menu');b?.setAttribute('aria-expanded',String(state.menu));return;}
 if(action==='sidebar-collapse'){state.sidebarCollapsed=!state.sidebarCollapsed;await render();return;}
 if(action==='sidebar-collapse'){state.sidebarCollapsed=!state.sidebarCollapsed;await render();return;}
 if(action==='new-general'||action==='new-sandbox'){await newChat(action==='new-general'?'general':'sandbox');return;}
 if(action==='audit'||action==='accounts'){nav(action);return;}
 if(action==='start-agent'){await newChat('agent',target.dataset.id);return;}
 if(action==='sample'){document.querySelector('#message').value='¿Cómo podría organizar mis ideas en este espacio?';document.querySelector('#message').focus();return;}
 if(action==='save-chat'){const c=await api.request('GET',`/chats/${state.chatId}`);await api.request('POST',`/chats/${c.id}/save`,{category:c.category,expectedRevision:c.revision});await render();toast('Guardado en el historial de la demo. No se ha añadido conocimiento.');return;}
 if(action==='categorize'||action==='promote'){const c=await api.request('GET',`/chats/${state.chatId}`);modal(action==='promote'?'Continuar con otro agente':'Guardar en una categoría',`<p class="modal-copy">${action==='promote'?'Se crea una conversación nueva. La original no cambia de permisos. El texto importado se trata como contenido no confiable.':'Solo cambia la clasificación en el historial. Un chat Sandbox continúa siendo Sandbox.'}</p><form data-form="${action}"><label class="field">Destino<select name="target">${options(c.category)}</select></label><div class="note-box">${action==='promote'?'La nueva conversación empieza sin guardar. No se transfieren cookies, herramientas, credenciales ni archivos.':'Guardar no añade el contenido a la memoria personal.'}</div><div class="modal-footer"><button class="btn primary" type="submit">${action==='promote'?'Crear nueva conversación':'Guardar aquí'}</button></div></form>`);return;}
 if(action==='discard'){modal('Descartar esta conversación',`<p class="modal-copy">Se eliminará de la memoria de esta demo. Esta acción no afecta a ninguna cuenta externa.</p><div class="modal-footer">${btn('Cancelar','close')}${btn('Descartar','confirm-discard','danger')}</div>`);return;}
 if(action==='confirm-discard'){await api.request('DELETE',`/chats/${state.chatId}`);state.chatId=null;dialog.close();nav('history');toast('Conversación descartada.');return;}
 if(action==='extract'){modal('Proponer conocimiento',`<p class="modal-copy">Escribe una nota de prueba. Se guardará como propuesta pendiente, separada del historial. No hay extracción por IA en esta demo.</p><form data-form="knowledge"><label class="field">Título<input name="title" maxlength="120" required></label><label class="field">Nota<textarea name="content" maxlength="8000" required></textarea></label><div class="modal-footer"><button class="btn primary" type="submit">Crear propuesta</button></div></form>`);return;}
 if(action==='approve-note'){await api.request('POST',`/knowledge/${target.dataset.id}/approve`,{});await render();toast('Nota de ejemplo aprobada.');return;}
 if(action==='new-task'){modal('Nueva tarea',`<form data-form="task"><label class="field">Qué hay que hacer<input name="title" required maxlength="200" placeholder="Una tarea de ejemplo…"></label><label class="field">Categoría<select name="category">${options('personal')}</select></label><div class="modal-footer"><button class="btn primary" type="submit">Crear en la demo</button></div></form>`);return;}
 if(action==='new-event'){eventModal();return;}
 if(action==='integration'||action==='nextcloud'){const id=action==='nextcloud'?'nextcloud':target.dataset.id;modal(`Integración: ${id}`,`<p class="modal-copy">Estado: pendiente de implementación y pruebas con el servicio real.</p><pre class="code">UI → Lisa API → autorización → adaptador\n\n${e(id)}\n\nSin tokens ni credenciales en el frontend.\nLa conexión se configurará en el servidor.</pre><p class="modal-copy">Las capacidades se publicarán desde /api/v1/bootstrap. El contrato completo está en contracts/openapi.mjs y en la especificación del repositorio.</p>${btn('Conexión no disponible en demo','none','','disabled')}`);return;}
 if(action.startsWith('computer-')){const transitions={'computer-wait':'waiting','computer-take':'human','computer-release':'waiting','computer-stop':'paused'};state.computer=transitions[action];api.log('computer.simulation',state.computer);await render();toast('Transición visual simulada. No se ha controlado ningún ordenador.');return;}
 if(action==='dev-proposal'){modal('Proponer un cambio de interfaz',`<form data-form="developer"><label class="field">Describe el cambio<textarea name="content" maxlength="4000" required placeholder="Por ejemplo: añadir una vista de documentos pendientes…"></textarea></label><div class="note-box">Se mostrará una propuesta visual. No se ejecutarán comandos, cambios en Git ni despliegues.</div><div class="modal-footer"><button class="btn primary" type="submit">Revisar propuesta</button></div></form>`);return;}
 if(action==='reset'){modal('Reiniciar la demostración',`<p class="modal-copy">Se borrarán las conversaciones, notas y cambios de esta demo. Los ejemplos iniciales volverán a aparecer.</p><div class="modal-footer">${btn('Cancelar','close')}${btn('Reiniciar','confirm-reset','danger')}</div>`);return;}
 if(action==='confirm-reset'){api.reset();state.chatId=null;dialog.close();nav('home');toast('Demo reiniciada.');return;}
 if(action==='check-api'){try{await new HttpClient().request('GET','/bootstrap');toast('La API ha respondido. El frontend sigue en modo demo.');}catch(error){toast(`API no conectada: ${error.message}`);}return;}
 if(action==='download-checklist'){const body='# Auditoría Lisa v0.3\n\n- [ ] Crear ambos modos de chat\n- [ ] Guardar sin añadir memoria\n- [ ] Categorizar Sandbox sin elevar permisos\n- [ ] Continuar en un agente: nuevo ID y original intacto\n- [ ] Proponer y aprobar conocimiento\n- [ ] Crear y completar tarea\n- [ ] Navegar calendario y crear evento ficticio\n- [ ] Filtrar y previsualizar archivos ficticios\n- [ ] Revisar permisos e integraciones no conectadas\n- [ ] Probar móvil, teclado y modo oscuro\n- [ ] Ver transición visual de takeover\n- [ ] Ver propuesta de desarrollo sin ejecución\n- [ ] Recargar elimina todo el estado demo\n';const url=URL.createObjectURL(new Blob([body],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='lisa-auditoria.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
}
document.addEventListener('click',async ev=>{const target=ev.target.closest('button');if(!target||target.disabled)return;try{
 if(target.dataset.nav){nav(target.dataset.nav);return;}
 if(target.dataset.new){await newChat(target.dataset.new);return;}
 if(target.dataset.agent){await newChat('agent',target.dataset.agent);return;}
 if(target.dataset.chat){state.chatId=target.dataset.chat;nav('chat');return;}
 if(target.hasAttribute('data-category')){state.category=target.dataset.category;await render();return;}
 if(target.dataset.task){await api.request('PATCH',`/tasks/${target.dataset.task}`,{done:target.dataset.done!=='true'});await render();return;}
 if(target.dataset.file){const f=await api.request('GET',`/files/${target.dataset.file}`);modal(f.name,`<p class="modal-copy">Vista de contenido ficticio, no un archivo real.</p><pre class="code">${e(f.content)}</pre><p class="resource-line">ID: ${e(f.id)} · versión ${f.version} · ${e(area(f.category).name)}</p>`);return;}
 if(target.dataset.month){state.month+=Number(target.dataset.month);if(state.month<0){state.month=11;state.year--;}if(state.month>11){state.month=0;state.year++;}await render();return;}
 if(target.dataset.date){eventModal(target.dataset.date);return;}
 if(target.dataset.action)await handleAction(target.dataset.action,target);
 }catch(error){toast(error.message||'No se pudo completar la acción.');}});
document.addEventListener('submit',async ev=>{const form=ev.target;if(!form.dataset.form)return;ev.preventDefault();const body=Object.fromEntries(new FormData(form));const kind=form.dataset.form;try{
 if(kind==='message'){if(state.busy)return;state.busy=true;const submit=form.querySelector('button[type="submit"]');submit.disabled=true;try{await api.request('POST',`/chats/${state.chatId}/messages`,{content:body.content});}finally{state.busy=false;submit.disabled=false;}await render();document.querySelector('#message')?.focus();return;}
 if(kind==='search'){state.filter=body.query;await render();return;}
 if(kind==='categorize'){const c=await api.request('GET',`/chats/${state.chatId}`);await api.request('POST',`/chats/${c.id}/save`,{category:body.target,expectedRevision:c.revision});dialog.close();await render();toast('Clasificado sin cambiar el modo ni los permisos.');return;}
 if(kind==='promote'){const c=await api.request('POST',`/chats/${state.chatId}/promotions`,{target:body.target,selectedAttachmentIds:[]});state.chatId=c.id;dialog.close();await render();toast('Nueva conversación creada. La original no ha cambiado.');return;}
 if(kind==='knowledge'){await api.request('POST',`/chats/${state.chatId}/knowledge-proposals`,body);dialog.close();nav('knowledge');toast('Propuesta creada; falta tu aprobación.');return;}
 if(kind==='task'){await api.request('POST','/tasks',body);dialog.close();await render();toast('Tarea creada en la demo.');return;}
 if(kind==='event'){await api.request('POST','/events',body);dialog.close();await render();toast('Evento de ejemplo creado.');return;}
 if(kind==='developer'){dialog.close();modal('Propuesta · sin ejecutar',`<p class="modal-copy">${e(body.content)}</p><pre class="code">Estado: propuesta de demostración\nDestino: nueva rama de código\nDatos: solo fixtures\nValidaciones: tests, diff, preview\nPublicación: aprobación humana</pre><div class="modal-footer">${btn('Cerrar','close')}${btn('Aplicar · backend pendiente','none','primary','disabled')}</div>`);return;}
 }catch(error){toast(error.message||'No se pudo completar la operación.');}});
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(views[v]){state.view=v;render().catch(err=>toast(err.message));}});
const initial=location.hash.slice(1);if(views[initial])state.view=initial;
render().catch(error=>{mount.textContent=`No se pudo iniciar Lisa: ${error.message}`;});
